### ISSUE TITLE
Is this repo ready to give it a try?

### ISSUE THREAD

**Issue by haoxins** [argoflow/argoflow-gcp#46]
Hi, @DavidSpek 

Thanks so much for this repository!

I have deployed my Kubeflow cluster used [gcp-blueprints](https://github.com/kubeflow/gcp-blueprints) on GKE.
But it's not an easy way to repeat the deployment.
I need to deploy multi Kubeflow clusters in different regions for a different purposes.
And your solution that uses ArgoCD seems very graceful.
We have used ArgoCD to deliver our services in production.

I know this repo is still **WIP**, but I really want to give it a try.

**So, my question is that is this repo the basically worked for deploying Kubeflow to GCP/GKE?**

And can you list the known issues in the readme document?
So that the other guys can be involved to give help.

**Comment by haoxins** [comment]
I have deployed the Kubeflow stack on my GCP/GKE cluster.
I think the answer to the question is absolute **YES**.

Thanks again for this repository and your contributions.

**Comment by DavidSpek** [comment]
@haoxins Sorry for the slow response. I've been very busy with a new platform that should make installing Kubeflow a whole lot easier. The installation should work on GCP, however, I've not yet started with any GCP specific integrations. The GCP-blueprints should provide most of the necessary manifests to do this though.

**Comment by haoxins** [comment]
> The GCP-blueprints should provide most of the necessary manifests to do this though.

I have deployed the Kubeflow clusters by both `argoflow-gcp` and `gcp-blueprints`.
And `argoflow-gcp` gives me the better experiences.

The `gcp-blueprints` use `kpt` and other GCP special APIs and GCP services, such as Cloud SQL.

We want to put all the Kubeflow components inside the K8s cluster.

So, I'm glad to contribute to this `argoflow-gcp` repo, and can you invite me to the `Kubeflow` stack.
Because the invitation URL in the Kubeflow website seems to be outdated.
